spring:
  redis:
    pool-config:
      max-total: 50
      max-idle: 10
    connect-timeout: 2000
    cluster:
      nodes:
        - noron-redis-dev:7000
        - noron-redis-dev:7001
        - noron-redis-dev:7002
        - noron-redis-dev:7003
        - noron-redis-dev:7004
        - noron-redis-dev:7005
      max-redirects: 3
    password: "Noron@2022"