spring:
  redis:
    pool-config:
      max-total: 50
      max-idle: 10
    connect-timeout: 2000
    cluster:
      nodes:
        - noron-redis:7000
        - noron-redis:7001
        - noron-redis:7002
        - noron-redis:7003
        - noron-redis:7004
        - noron-redis:7005
      max-redirects: 3
    password: "Noron@2022"