/*
 * This file is generated by jOOQ.
 */
package vn.noron.data.response.order;
import lombok.Data;
import lombok.experimental.Accessors;


/**
 * tài liệu đã mua trên hóa đơn
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Data
@Accessors(chain = true)
public class OrderProductResponse{

    private Integer id;
    private Integer reportId;
    private String  reportTitle;
//    private ShortReportResponse reportResponse;
    private Double  salePrice;
    private Integer orderId;
    private Integer productId;
    private String  productTitle;
//    private PackageResponse packageResponse;
    private Double  finalPrice;
    private String  productType;
    private String  discount;
    private Long    ownerId;

}
